version: "3.1"

services:
    mariadb:
        image: mariadb:lts-noble
        restart: always
        ports:
            - 3306:3306
        container_name: mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=toor
    phpmyadmin:
        image: phpmyadmin
        restart: unless-stopped
        ports:
            - 80:80
        environment:
            - PMA_HOST=mariadb
            - PMA_PORT=3306
        depends_on:
            - mariadb
